function dataSet = loadLbcbData(file, cps)
    s= '%s%s%s';
    s = [s,repmat('%f',1,42)]; % extra servo error headers
    hs = repmat('%s',1,49);
    fid = fopen(file, 'r');
    headers = textscan(fid,hs,1,'Delimiter','\t');
    headers{:}
    raw = textscan(fid, s);
    [raw_r,raw_c] = size(raw)
    
    % format of labels: long name, short name, dof type
    % dof types: 0=Time, 1=Dx,2=Dy,3=Dz,4=Rx,5=Ry,6=Rz
    %            7=Fx,8=Fy,9=Fz,10=Mx,11=My,12=Mz,13=SE
    labels = {'Cartesian Command','Dx',1;...
            'Cartesian Command','Dy',2;...
            'Cartesian Command','Dz',3;...
            'Cartesian Command','Rx',4;...
            'Cartesian Command','Ry',5;...
            'Cartesian Command','Rz',6;...
            'Cartesian','Dx',1;...
            'Cartesian','Dy',2;...
            'Cartesian','Dz',3;...
            'Cartesian','Rx',4;...
            'Cartesian','Ry',5;...
            'Cartesian','Rz',6;...
            'Cartesian','Fx',7;...
            'Cartesian','Fy',8;...
            'Cartesian','Fz',9;...
            'Cartesian','Mx',10;...
            'Cartesian','My',11;...
            'Cartesian','Mz',12;...
            'Actuator Command','Dx1',1;...
            'Actuator Command','Dx2',1;...
            'Actuator Command','Dy',2;...
            'Actuator Command','Dz1',3;...
            'Actuator Command','Dz2',3;...
            'Actuator Command','Dz3',3;...
            'Actuator Stroke','Dx1',1;...
            'Actuator Stroke','Dx2',1;...
            'Actuator Stroke','Dy',2;...
            'Actuator Stroke','Dz1',3;...
            'Actuator Stroke','Dz2',3;...
            'Actuator Stroke','Dz3',3;...
            'Actuator Force','Fx1',7;...
            'Actuator Force','Fx2',7;...
            'Actuator Force','Fy',8;...
            'Actuator Force','Fz1',9;...
            'Actuator Force','Fz2',9;...
            'Actuator Force','Fz3',9;...
            'Actuator SE','X1',13;...
            'Actuator SE','X2',13;...
            'Actuator SE','Dy',13;...
            'Actuator SE','Z1',13;...
            'Actuator SE','Z2',13;...
            'Actuator SE','Z3',13};
        
        setSize = length(raw{4});
        lbcbData = zeros(setSize,length(labels));
        for i=4:raw_c
               lbcbData(:,i-3) = raw{i};
        end
        dataSet = cell(length(labels) + 1,1);
        timeData = 1:setSize;
        p = plotData('Time','T','');
        p.addData(timeData);
        dataSet{1} = p;
        for i=1:length(labels)
            p = plotData(labels{i,1},labels{i,2},cps);
            p.addData(lbcbData(:,i));
            p.setDofType(labels{i,3});
            dataSet{i+1,1} = p;
        end        
end
