function createAbfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-Jan-2010 19:50:11

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[-10 -9.5 -9 -8.5 -8 -7.5 -7 -6.5 -6 -5.5 -5 -4.5 -4 -3.5 -3 -2.5 -2 -1.5 -1 -0.5 0 0.5 1 1.5 2 2.5 3 3.5 4 4.5 5 5.5 6 6.5 7 7.5 8 8.5 9 9.5 10],...
    'XTick',[0 2 4 6 8 10 12 14 16 18 20 22 24],...
    'Color',[0.9412 0.9412 0.9412]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'Marker','*','LineWidth',2);
set(plot1(1),'DisplayName','Hx1');
set(plot1(2),'Color',[0 0 1],'DisplayName','Lx1');
set(plot1(3),'Color',[0 0.498 0],'DisplayName','Hx2');
set(plot1(4),'Color',[0 0.498 0],'DisplayName','Lx2');
set(plot1(5),'Color',[1 0 0],'DisplayName','Hy1');
set(plot1(6),'Color',[1 0 0],'DisplayName','Ly1');
set(plot1(7),'Color',[0 0.749 0.749],'DisplayName','Hz1');
set(plot1(8),'Color',[0 0.749 0.749],'DisplayName','Lz1');
set(plot1(9),'Color',[0.749 0 0.749],'DisplayName','Hz2');
set(plot1(10),'Color',[0.749 0 0.749],'DisplayName','Lz2');
set(plot1(11),'Color',[0.749 0.749 0],'DisplayName','Hz3');
set(plot1(12),'Color',[0.749 0.749 0],'DisplayName','Lz3');

% Create xlabel
xlabel({'Samples'},'FontSize',14);

% Create ylabel
ylabel({'Command Voltages'},'FontSize',14);

% Create title
title({'Autobalance Algorithm Command Voltage Convergence'},'FontSize',18);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.2204 0.5281 0.03955 0.1997],'Color',[1 1 1]);

% Create line
annotation(figure1,'line',[0.1294 0.9067],[0.518 0.518],'LineStyle','--',...
    'LineWidth',3);

